#!/usr/bin/env pwsh

param ([string]$cmd, [string[]]$cmdargs)

$commands = @{
  build = {
    param ([switch] $open, [string[]] $args)

    $outputFilename = (Get-Location) + ".pdf"
    $cmd = {
      "pandoc ./*.md -f markdown -t pdf --filter pandoc-citeproc"
      "-o $outputFilename"
      if ($bib = (Get-Item *.bib)) { "--bibliography $bib" }
    }

    (&$cmd) -join ' ' | Invoke-Expression
    if ($open) { Invoke-Item $outputFilename }
  }

  watch = { 
    param ([string[]] $args)
    $fsw = [System.IO.FileSystemWatcher]@{ Path="." }
    $builder = { &$commands.build @args }
    foreach ($evt in @("Created","Renamed","Changed","Deleted")) {
      Register-ObjectEvent -InputObject $fsw -EventName $evt -Action $builder
    }
  }
}

&commands[$cmd] @cmdargs
