#!/usr/bin/env pwsh

param ([string]$cmd)

function build {
  param ([switch] $open)
  $arguments = $args
  $outputFilename = (Get-Item .).Name + ".pdf"
  $cmd = {
    "pandoc ./*.md -t latex"
    "-o $outputFilename"
    if ($bib = Get-Item *.bib) {
      "--bibliography $bib"
      "--filter pandoc-citeproc"    
    }
    "$($arguments -join " ")"
  }
  Write-Host (&$cmd)
  (&$cmd) -join ' ' | Invoke-Expression
  if ($open) { Invoke-Item $outputFilename }
}

function watch { 
  $fsw = [System.IO.FileSystemWatcher]@{ Path = "." }
  $builder = { build @args }
  foreach ($evt in @("Created", "Renamed", "Changed", "Deleted")) {
    Register-ObjectEvent -InputObject $fsw -EventName $evt -Action $builder
  }
}

$commands = @{
  build="build"
  watch="watch"
}

&$commands[$cmd] @args
